language: ruby
cache:
  bundler: true
  directories:
    - .jekyll-cache

bundler_args: "--without development --path .bundle"
rvm:
- 2.5.3
addons:
  ssh_known_hosts: ssh.xam.dk
branches:
  only:
  - master
before_script:
- sudo apt-get install -qq sshpass
script: bundle exec rake travis
env:
  global:
    secure: fpWVLgbveBCXlsXX7ef06qi7GrizwAE5MFq5pKH9G5AMFAdFL4xQxNOmeemRZ5fnMAn8LQUrA8otxwjiiq2RangRC9E11fBChEKC5V+FewBzsHONqkSTzKd6oAbmLynUizpXDofhVxIfRhtP03lfEDufzly4WaVDyoLJicvy9aM=

