indieweb:
  micropub: https://xamdk-micropub.now.sh/micropub/main
  token_endpoint: https://tokens.indieauth.com/token
  authorization_endpoint: https://indieauth.com/auth
  microsub: https://aperture.p3k.io/microsub/193

github: https://github.com/maxandersen/xam.dk

socialsites:
  - title: "me"
    url: "/about"
    avatar: "/avatar.jpg"
  - title: "twitter"
    url: "https://twitter.com/maxandersen"
  - title: "github"
    url: "https://github.com/maxandersen"
  - title: "linkedin"
    url: "https://linkedin.com/in/maxrydahlandersen"
  - title: "envelope"
    url: "mailto://max@xam.dk"
  - title: "facebook"
    url: "https://facebook.com/maxandersen"

