name: publish-to-xam.dk

on:
  push: 
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-publish
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - uses: actions/cache@v1
        with:
          path: .jekyll-cache
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - name: install dependencies
        run: |
          sudo apt-get install -qq sshpass
          ssh-keygen -R ssh.xam.dk
          gem install bundler
          mkdir -p vendor/bundle
          bundle config path vendor/bundle
          #bundle install
      - name: build-and-publish
        env:
          XAMSSH: "${{ secrets.XAMSSH }}"
        run: bundle exec rake travis
        